// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mail "2020_1_drop_table/internal/microservices/mail/delivery/grpc/proto"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MailGRPCServer is an autogenerated mock type for the MailGRPCServer type
type MailGRPCServer struct {
	mock.Mock
}

// SendEmail provides a mock function with given fields: _a0, _a1
func (_m *MailGRPCServer) SendEmail(_a0 context.Context, _a1 *mail.EmailParams) (*mail.Empty, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *mail.Empty
	if rf, ok := ret.Get(0).(func(context.Context, *mail.EmailParams) *mail.Empty); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mail.Empty)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *mail.EmailParams) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
