// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mail "2020_1_drop_table/internal/microservices/mail/delivery/grpc/proto"

	mock "github.com/stretchr/testify/mock"
)

// MailGRPCClient is an autogenerated mock type for the MailGRPCClient type
type MailGRPCClient struct {
	mock.Mock
}

// SendEmail provides a mock function with given fields: ctx, in, opts
func (_m *MailGRPCClient) SendEmail(ctx context.Context, in *mail.EmailParams, opts ...grpc.CallOption) (*mail.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *mail.Empty
	if rf, ok := ret.Get(0).(func(context.Context, *mail.EmailParams, ...grpc.CallOption) *mail.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mail.Empty)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *mail.EmailParams, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
