version: "3"

volumes:
  dbbackups:
  postgis-data:

#change ports to expose in microservices
#change name of main_service to main
services:
#  Microservices
  main_service:
    image: main_service
    ports:
      - "8080:8080"
      - "8082:8082"
    env_file:
      - envs/golang.env
    volumes:
      - $PWD/media:/app/media
    depends_on:
      - redis
      - postgres

  staff:
    image: staff_service
    env_file:
      - envs/golang.env
    ports:
      - "8084:8084"
      - "8083:8083"
    volumes:
      - $PWD/media:/app/media
    depends_on:
      - redis
      - postgres

  survey:
    image: survey_service
    env_file:
      - envs/golang.env
    ports:
      - "8085:8085"
      - "8086:8086"
    volumes:
      - $PWD/media:/app/media
    depends_on:
      - redis
      - postgres
# Databases
  redis:
    image: "redis:alpine"
    command: ["redis-server"]
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
    environment:
      - REDIS_REPLICATION_MODE=master

  postgres:
    image: kartoza/postgis:12.0
    volumes:
      - postgis-data:/var/lib/postgresql
      - $PWD/docker/postgres_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - envs/postgres.env
    ports:
      - "5432:5432"
    restart: on-failure
    healthcheck:
      test: "exit 0"
# Monitoring
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus:/etc/prometheus/
      - ./monitoring/data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    restart: always
    user: "0"
    depends_on:
      - alertmanager

  node_exporter:
    image: prom/node-exporter
    expose:
      - 9100

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    user: "0"
    volumes:
      - ./monitoring/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
        - prometheus

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - ./monitoring/data/alertmanager:/data
    command:
      - '--config.file=/etc/prometheus/alertmanager.yml'
      - '--storage.path=/data'
    ports:
      - "9093:9093"

  alertmanager-bot-telegram:
    command:
      - --log.level=info
      - --store=bolt
      - --bolt.path=/data/bot.db
    env_file:
      - envs/telegram.env
    image: metalmatze/alertmanager-bot:0.4.2
    ports:
      - "9095:9095"
    restart: always
    volumes:
      - ./monitoring/data/alertmanager-bot-telegram:/data
      - ./monitoring/prometheus/:/configs
    depends_on:
      - alertmanager

  redis_exporter:
    image: oliver006/redis_exporter
    command: -redis.addr redis://redis:6379
    ports:
      - "9121:9121"

  postgres_exporter:
    image: wrouesnel/postgres_exporter
    env_file:
      - envs/postgres_exporter.env
    ports:
    - "9187:9187"
