groups:
  - name: AllInstances
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Контейнер {{ $labels.instance }} упал"
          description: "{{ $labels.instance }} не отвечает {{ $labels.job }}'у больше 30 секунд."
